services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    
    volumes:
      - ./:/app
    
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  db:
    image: ankane/pgvector:v0.5.1
    restart: always
    # environment:
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    #   POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: